# Odin1 建图模式配置。
# 绑定关系：custom_map_mode: 1 = SLAM 建图模式。
# 保存地图时不要直接退出驱动，另开终端执行：
# cd <odin_ws>/src/odin_ros_driver && ./set_param.sh save_map 1

register_keys:
  strict_usb3.0_check: 1
  use_host_ros_time: 0

  map_frame: "odin1_map"
  odom_frame: "odin1_odom"
  imu_frame: "odin1_imu"
  lidar_frame: "odin1_lidar"
  camera_frame: "odin1_camera"

  streamctrl: 1

  sendrgbcompressed: 1
  sendrgb: 1
  sendrgbundistort: 0

  sendimu: 1
  enable_imu_smooth: 0
  imu_smooth_frequency: 400

  sendodom: 1
  sendodomhighfreq: 1
  sendodomtfstream: 1
  sendwiwc: 1
  send_odom_baselink_tf: 1
  tf_extra_publish_rate: 0

  senddtof: 1
  cloud_raw_confidence_threshold: 35
  dtof_fps: 100

  sendcloudslam: 1
  sendcloudrender: 1

  senddepth: 0
  sendreprojection: 0
  sendoverlay: 0
  overlay_reprojected_topic: "/odin1/reprojected_image"
  overlay_camera_topic: "/odin1/image/undistorted"
  overlay_output_topic: "/odin1/overlay_image"
  overlay_alpha: 0.6

  recorddata: 1
  devstatuslog: 1
  save_log: 0
  sdk_log_level: 0

  pubintensitygray: 0
  showpath: 1
  showcamerapose: 0

  custom_map_mode: 1
  custom_init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
  custom_init_pose_search_radius: 4.0
  custom_init_pose_max_rot_deg: 180.0
  relocalization_map_abs_path: ""

  mapping_result_dest_dir: ""
  mapping_result_file_name: ""

  sendimagemask: 0
  image_mask_abs_path: ""
  resetalgo: 0
